### ISSUE TITLE
Create Presentation

### ISSUE THREAD

**Issue by nazariusPr** [EventHub-org/BookHub#1]
The goal of the **"Create Presentation"** task is to design and develop a well-structured, visually appealing presentation that effectively conveys key information to an audience. This task typically involves the following steps

**Comment by viktorpekhun** [comment]
Презентація доступна за посиланням:
[https://www.canva.com/design/DAGQ1hRA8AU/iuw5GvE6zTJkNd2WJrHY1g/edit?utm_content=DAGQ1hRA8AU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton](url)
